# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MINQUE0 <- function(KList, y) {
    .Call(`_KernelNN_MINQUE0`, KList, y)
}

MINQUE <- function(KList, y, prior) {
    .Call(`_KernelNN_MINQUE`, KList, y, prior)
}

IMINQUE <- function(KList, y, prior, epoch = 100L, threshold = 1e-4, echo = FALSE) {
    .Call(`_KernelNN_IMINQUE`, KList, y, prior, epoch, threshold, echo)
}

MNQTest0_Overall <- function(KList, vcs, wgt) {
    .Call(`_KernelNN_MNQTest0_Overall`, KList, vcs, wgt)
}

MNQTest0_Component <- function(KList, vcs, vcs_h0, index_interest, wgt) {
    .Call(`_KernelNN_MNQTest0_Component`, KList, vcs, vcs_h0, index_interest, wgt)
}

IMNQTest_Normal <- function(KList, vcs, index_interest) {
    .Call(`_KernelNN_IMNQTest_Normal`, KList, vcs, index_interest)
}

